hashicorp/tfc-workflows-tooling

- CODEOWNERS
TF-VCS is now TF-Nexus. This change updates codeowners to reflect that.
> Updated codeowners to reflect new team name

- internal/command/plan_output.go
- internal/command/run_apply.go
- internal/command/run_cancel.go
- internal/command/run_create.go
- internal/command/run_discard.go
- internal/command/run_show.go
- internal/command/upload.go
From mitchellh/cli `Command.Synopsis()` is supposed to output a [single line](https://github.com/mitchellh/cli/blob/v1.1.5/command.go#L28-L30), as the `Command.Help()` is used when requesting detailed help about a specific command. This corrects all the existing `Synopsis()` implementations.
This fixes #13.
This change also addresses some formatting inconsistencies: commands are standardized on ending their `Help()` synopsis output with a period, but some were missing.
1. `TF_API_TOKEN=abc go run . -- run`
2. See the following output:
```
This command is accessed by using one of the subcommands below.
Subcommands:
apply      Applies a run that is paused waiting for confirmation after a plan
cancel     Interrupts a run that is currently planning or applying
create     Performs a new plan …
```
> Make `Command.Synopsis()` implementations one line

- CHANGELOG.md
- internal/cloud/run.go
Fixes issue for workspaces with auto apply enabled, executing the `run create` command and failing to quit gracefully.
Also including some changelog entries. We should start requesting for any code changes going forward.
Addresses Issue: #15 
1.  Setup a Terraform Cloud workspace with auto apply enabled
1.  Issue the `run create` command with appropriate flags
1.  Confirm command successfully shuts down and does not continue to run.
> Fix create run command to account for auto apply workspaces

- CHANGELOG.md
Releases dependency updates to `go-tfe`.
There are also pending PRs on the dependant repositories for the `v1.0.2` release:
* https://github.com/hashicorp/tfc-workflows-github/pull/11
* https://github.com/hashicorp/tfc-workflows-gitlab/pull/8
Specifically to pick up https://github.com/hashicorp/go-tfe/pull/717.
> Prepare for v1.0.2

- CHANGELOG.md
- internal/cloud/run.go
Add `policy_soft_failed` status to desired status slice to be treated as `Success`.
> add 'policy_soft_failed' to desired status

- CHANGELOG.md
- internal/cloud/run.go
* Fix issue with attempting to read sentinel policy logs that never ran from blocking execution.
* Only log to stdout cost estimation / sentinel policies that have ran.
> Fix unreached sentinel policies blocking log read to stdout

- .gitignore
- CHANGELOG.md
- internal/command/meta.go
- internal/command/output.go
- internal/command/plan_output.go
- internal/command/run_create.go
- internal/command/run_show.go
- internal/command/upload.go
- internal/environment/env.go
- internal/environment/github.go
- internal/environment/github_test.go
- internal/environment/gitlab.go
- internal/environment/gitlab_test.go
Refactoring output handling with the following goals:
* Removal of hardcoded output key values containing possible multi line strings for certain CI platforms. e.g `payload`
* Separation of output values for stdout vs platform outputs. (github, gitlab)
> Refactor for output interface

- cli.go
- internal/cloud/cloud.go
- internal/cloud/workspace.go
- internal/cloud/workspace_test.go
- internal/command/workspace_output.go
- internal/command/workspace_output_test.go
Adds new `workspace output list` command. 
* `--workspace` name of the existing Terraform Cloud workspace.
* `outputs`[] json array consisting of current outputs for the provided Terraform Cloud workspace. (sensitive values are returned as `null`)
* `status` of the operation.
* #9
> Add workspace output list command

- CHANGELOG.md
- internal/command/plan_output.go
- internal/command/run_create.go
- internal/command/run_show.go
- internal/command/upload.go
Fixes Issue #45  that was introduced in [v1.0.3](https://github.com/hashicorp/tfc-workflows-tooling/releases/tag/v1.0.3). 
Missed instances of zero value for bool field when adding artifact to output.
- Merge this fix into main
- Back-port and patch a release for v1.0.4 since main includes new additions for next minor release
> Fix missing default for platformOut option

- docs/USAGE.md
Terraform Enterprise owners usually sign Terraform Enterprise TLS certificates with a private CA. Attempting to use tfci to interact with a Terraform Enterprise API in this way will cause an x509 error. A custom container image can be built from the hashicorp/tfci container with the CA certificate included to enable trust between the tfci container running in the pipelines and Terraform Enterprise.
1. Create a Terraform Enterprise server signed by a private CA or self signed certificate
2. Create a custom image from the hashicorp/tfci container and provide the CA certificate
3. Run the tfci container and attempt to interact with the Terraform Enterprise API
> Instructions for use with Terraform Enterprise Added to USAGE.md

- CHANGELOG.md
- internal/cloud/run.go
- internal/cloud/run_test.go
As reported by #49, prevent workspaces configured with `AutoApply` from exiting `create run` command too early. 
- This is a hard scenario to replicate consistently. Best option is to vet any possible regressions.
> fix: Prevent Auto-Apply TFC workspaces from exiting early for `run create` cmd

- .github/actions/test-create-run/action.yml
- .github/actions/test-upload-configuration/action.yml
- .github/actions/test-workspace-output/action.yml
- internal/command/workspace_output.go
`outputs` json array is currently being omitted from being sent to github/gitlab output mistakenly. Due to zero value of boolean being false (Not to be confused w/ stdout)
Will need to cut another release before rolling out to github & gitlab repositories.
> fix: workspace output list command option to include with platform output

- cli.go
- internal/cloud/cloud.go
- internal/cloud/configuration_version.go
- internal/cloud/configuration_version_test.go
- internal/cloud/plan.go
- internal/cloud/run.go
- internal/cloud/run_test.go
- internal/cloud/tfe_client.go
- internal/cloud/workspace.go
- internal/cloud/workspace_test.go
- internal/command/meta.go
- internal/command/plan_output.go
- internal/command/run_apply.go
- internal/command/run_cancel.go
- internal/command/run_create.go
- internal/command/run_discard.go
- internal/command/run_show.go
- internal/command/upload.go
- internal/command/upload_test.go
- internal/command/workspace_output.go
- internal/command/workspace_output_test.go
- internal/writer/writer.go
- main.go
Add support for other command line tools such as `jq` by allowing a global `--json` flag argument.
Currently, we are outputting some in-progress/diagnostic information to stdout rather than to stderr. When a `--json` flag is detected regardless of position, we will send all information that is not the final result set to the standard error stream.
A new [writer](https://github.com/hashicorp/tfc-workflows-tooling/blob/0c61894f699825c228be23f6bd74e3dbd4f6cd38/internal/writer/writer.go#L12) package has been added to allow for better dependency injection for other packages.
1. Execute various commands **without** the use of `--json` flag. No change in behavior and output.
1. Run and verify the following script works as expected, where the apply succeeds.
<details>
<summary>script.sh</summary> …
> feat: allow global --json flag usage

- CHANGELOG.md
- internal/cloud/run_test.go
* Moves changelog entry to unreleased enhanced section
* Fixes runs mock service to represent new saved plan option
> fix: broken test mock service

- .github/workflows/e2e.workflow.yml
Previous matrix strategy resulted in null/blank option for save_plan with create-run action
- [GitHub Actions Matrix Docs](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations)
- [Failed scheduled job](https://github.com/hashicorp/tfc-workflows-tooling/actions/runs/6887178566)
> fix: e2e workflow matrix strategy

- .gitignore
- CHANGELOG.md
This PR adds the tfci binary to .gitignore to ensure that it is not accidentally included in any future PRs
1. Run "go build" from the root directory of this repo
2. Observe that the generated tfci binary is not tracked by git.
> Add tfci binary to .gitignore

- CHANGELOG.md
- docs/ADOPTION.md
- internal/cloud/run.go
- internal/cloud/run_test.go
- internal/command/run_create.go
This pull request adds the capability to create a destroy run by setting the `data.attributes.is-destroy` key.
<br class="Apple-interchange-newline">
1.  Build tfci, `go build`
2. `export TF_API_TOKEN=<TOKEN>`
3. `export TF_CLOUD_ORGANIZATION=<ORG>`
4. Run tfci, `tfci -hostname=terraform.duke-energy.com -organization=rdpautomation-test run create -workspace=airflow-sbx -is-destroy=true
- [API documentation](https://developer.hashicorp.com/terraform/enterprise/api-docs/run#request-body)
- [tfe GO package, RunCreateOptions](https://pkg.go.dev/github.com/hashicorp/go-tfe#RunCreateOptions)
> Adding Adds support for Terraform destroy under  command

- docs/RELEASES.md
Adds release process and guidelines
> docs: add release process

- docs/RELEASES.md
Adds sections for GitHub and GitLab for the release process
> docs: add sections for github and gitlab

- CHANGELOG.md
- docs/ADOPTION.md
- internal/cloud/run.go
- internal/cloud/run_test.go
- internal/command/run_create.go
This pull request adds the capability to create a Terraform run using the target option to focus Terraform to specific resources.
Build tfci, go build
`export TF_API_TOKEN=<TOKEN>`
`export TF_CLOUD_ORGANIZATION=<ORG>`
Run tfci, `tfci -hostname=<HOST> -organization=<ORG> run create -workspace=<WORKSPACE> -target-addr=aws_instance.foo`
- [Command: plan | Terraform](https://developer.hashicorp.com/terraform/cli/commands/plan#resource-targeting)
- [tfe golang package: RunCreationOptions](https://pkg.go.dev/github.com/hashicorp/go-tfe#RunCreateOptions)
> Adding support for Terraform plan target

- internal/command/run_create.go
Fixes case where a user may pass a `--target=` or `--target=""` argument.
Prior, if an argument was empty we would allocate a slice with an empty string, causing go-tfe sdk to include TargetAddrs with the request, resulting in a failed run.
1. Create a run with --target= or --target=""
2. With fix, verify run completes successfully
> fix: omit empty target argument

- CHANGELOG.md
- Dockerfile
Removes `GOARCH` to ensure the Go toolchain does not cross compile, ensures the Go toolchain compiles for the local platform. When running on amd64 this results in an amd64 build, and on armv8 this results in an armv8 build.
I can reproduce building the amd64 version of `tfci` on an arm machine:
```
> uname -a
Darwin giannigambetti-QWX723M2KW 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
> docker buildx build .
> docker create <image-id>
> docker cp <container-id>:/usr/local/bin/tfci .
> file tfci
```
Before removing `GOARCH`: `tfci: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=DffVugsDq3wO1Mk_H00e/2vP_KXpCh8-ymBb5vwvs/AH6cx2NYXgnKG7YZLVF4/TtOShnVZAi2meWCOGZcy, stripped`
After …
> Avoids cross compilation in Dockerfile

- CHANGELOG.md
- internal/cloud/run.go
Fixes #136 
simply execute `tfci run create` in a workspace that already has a post-plan job.
> 🐛 Add "post_plan_completed" to the desired states

- CHANGELOG.md
- go.sum
Prepares changelog entry and dependency cleanup for v.1.3.3 release.
Includes go language version bump from 1.18 to 1.23. See related #141.
> Prepare v1.3.3 Release

- .github/actions/test-create-run/action.yml
- internal/cloud/run.go
- internal/cloud/run_test.go
- internal/command/run_create.go
Include the option to set `refresh` in order to skip checking for external changes to remote objects while creating the plan (same behaviour as executing terraform cli with `-refresh=value`.
This PR fixes #151 issue.
Included a test to include `-refresh=false` in the run creation.
- [Blog entry for terraform cli](https://www.hashicorp.com/en/blog/new-terraform-planning-options-refresh-false-refresh-only-replace)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run) : included data.attributes.refresh` parameter.
> Add refresh option
