hashicorp/tfc-workflows-tooling

CHANGELOG.md
Add `CHANGELOG.md` file for future releases.
=> add changelog for future releases

CHANGELOG.md
Adds entry for [go-tfe v1.29.0](https://github.com/hashicorp/go-tfe/releases/tag/v1.29.0) bump to changelog.
=> Update Changelog entry for go-tfe version bump (v1.29.0)

CHANGELOG.md, internal/cloud/configuration_version.go, internal/cloud/plan.go, internal/cloud/run.go
Output additional error log messages when interacting with TFC/E
=> Output additional error log messages when interacting with TFC/E

CHANGELOG.md
Prepare changelog for v1.0.3 release
=> Prepare for v1.0.3 release

.github/workflows/call-jira-issue-sync.workflow.yml, .github/workflows/jira-issues-sync.workflow.yml
Adds reusable workflow to sync issues to our ticketing system.
`.github/workflows/jira-issues-sync.workflow.yml` workflow file can be called from our downstream repositories.
=> Add workflow to sync issues

.github/workflows/jira-issues-sync.workflow.yml
=> Fix github action workflow

.github/workflows/call-jira-issue-sync.workflow.yml
=> Add missing inherit secrets for callable workflow

.github/workflows/jira-issues-sync.workflow.yml
=> Remove Jira component from action workflow

.github/workflows/call-jira-issue-sync.workflow.yml
=> Chore: Fix epic link field

CHANGELOG.md
Updating changelog.md for `v1.1.0`
=> Prepare for v1.1.0

cli.go, internal/cloud/cloud.go, internal/cloud/configuration_version.go, internal/cloud/configuration_version_test.go, internal/cloud/plan.go, internal/cloud/run.go, internal/cloud/run_test.go, internal/cloud/workspace.go, internal/cloud/workspace_test.go, internal/command/meta.go, internal/command/plan_output.go, internal/command/run_apply.go, internal/command/run_cancel.go, internal/command/run_create.go, internal/command/run_discard.go, internal/command/run_show.go, internal/command/upload.go, internal/command/upload_test.go, internal/command/workspace_output.go, internal/command/workspace_output_test.go, internal/writer/writer.go
Pointing to existing branch to better compare requested changes
=> chore: cleanup json flag behavior

docs/ADOPTION.md, docs/USAGE.md
Documentation enhancements for users and partners
=> docs: add adoption guide and revamp usage documentation

CHANGELOG.md
Prepare v1.1.1 release with included enhancements and fixes
=> Prepare release v1.1.1

.github/workflows/e2e.workflow.yml
Fixes recent regression for github actions workflow for e2e tests.
=> chore: fix broken e2e tests

.github/actions/test-create-run/action.yml
Fixes typo in our test-create-run action.yml file
- [Verified Fix](https://github.com/hashicorp/tfc-workflows-tooling/actions/runs/6895014629)
=> fix: input typo for test-create-run action

CHANGELOG.md
This PR updates the changelog in preparation for the 1.2.0 release.
=> Prepare 1.2.0 release

CHANGELOG.md
Prepares changelog for upcoming release.
=> Prepare v1.3.0 release

.github/actions/test-create-run/action.yml, .github/actions/test-plan-output/action.yml, .github/actions/test-upload-configuration/action.yml, .github/actions/test-workspace-output/action.yml, CHANGELOG.md, README.md, cli.go, docs/ADOPTION.md, docs/USAGE.md, internal/cloud/run.go, internal/cloud/tfe_client.go, internal/command/meta.go, internal/command/plan_output.go, internal/command/run_apply.go, internal/command/run_cancel.go, internal/command/run_create.go, internal/command/run_discard.go, internal/command/run_show.go, internal/command/upload.go, internal/command/workspace_output.go
Updates documentation and references to HCP Terraform
- [tfc-workflows-github PR](https://github.com/hashicorp/tfc-workflows-github/pull/45)
=> docs: HCP Terraform rebrand

docs/ADOPTION.md
=> Fix links in ADOPTION.md

CHANGELOG.md
Preparing CHANGELOG.md entries for v1.3.1 release
=> chore: prepare v1.3.1 release

CHANGELOG.md
Prepares release v.1.3.2 that includes bug fix and dependency bump
=> chore: prepare v1.3.2 release
